
import { getGithubUserAndRepos, analyzeLanguages } from '@/lib/github';
import { notFound } from 'next/navigation';
import { PortfolioView } from './_components/portfolio-view';

export const revalidate = 3600; // Revalidate the data at most once per hour

export async function generateMetadata({ params }: { params: { username: string } }) {
  try {
    const { user } = await getGithubUserAndRepos(params.username);
    const title = user.name ? `${user.name} (@${user.login})` : params.username;
    return {
      title: `${title} | Gitfolio`,
      description: user.bio || `The developer portfolio for ${title}, generated by Gitfolio.`,
    };
  } catch (error) {
    return {
      title: 'User Not Found | Gitfolio',
      description: 'Could not find the specified GitHub user.',
    };
  }
}

export default async function PortfolioPage({ params }: { params: { username: string } }) {
  const { username } = params;
  let userData;

  try {
    userData = await getGithubUserAndRepos(username);
  } catch (error) {
    console.error(error);
    if ((error as Error).message.includes('not found')) {
      notFound();
    }
    // For other errors, we can proceed without user data
    userData = userData || { user: { login: username }, repos: [] };
  }

  const { user, repos } = userData;
  const languageData = analyzeLanguages(repos);
  
  // Prepare a smaller, stringified version of repos for the AI summary prompt
  const reposForAISummary = repos.slice(0, 20).map(repo => ({
    name: repo.name,
    description: repo.description,
    language: repo.language,
    stars: repo.stargazers_count,
    forks: repo.forks_count,
  }));
  const reposJson = JSON.stringify(reposForAISummary, null, 2);

  return (
    <PortfolioView 
      user={user}
      repos={repos}
      languageData={languageData as any}
      reposJson={reposJson}
      username={username}
    />
  );
}
